### ISSUE TITLE
Improve CSS file

### ISSUE THREAD

**Issue by e2jk** [technext/Attorney#16]
Aside from identifying and fixing the error, this issue is probably low priority.
Running the `style.css` file through http://csslint.net/ returns the following:

> CSS lint found 1 errors and 244 warnings. How can you fix it? See the details below.

The error is `Unexpected token '{' at line 661, col 2.` I could not determine that myself, but I suppose there is a missing `}` somewhere in the file?

When allowing `!important`, the number of warnings goes down to 169.

Two summaries at the end:

> Disallow too many font sizes
> Too many font-size declarations (53), abstraction needed.
> 
> Headings should only be defined once
> You have 5 h1s, 3 h2s, 11 h3s, 4 h4s, 2 h5s, 3 h6s defined in this stylesheet.

**Comment by mahmud2011** [comment]
1. CSS errors fixed.
2. We are not dealing with the css warnings now as it won't effect the website.

Thanks. We appreciate your concern @e2jk.
