### ISSUE TITLE
When in mobile mode, clicking on a menu item should make the menu disappear

### ISSUE THREAD

**Issue by e2jk** [technext/Attorney#7]
When resizing the browser to a small width, the menu on top becomes a mobile-friendly menu.
When clicking on the button with the 3 bars, you get the menu. If you select one of the options, the page scrolls to that place. All fine until then.
However, the menu remains open, which forces the user to press the menu button once more.

Could the menu be closed once one of the menu item has been clicked?

**Comment by prium** [comment]
Hi,
It's about UX. I need some expert opinion about it. Let me discuss with the team and let you know what they think. 
Thanks

**Comment by e2jk** [comment]
When discussing this, please take into account what the default Bootstrap
theme does in this situation, as they've already had to face this (hint:
the menu closes ;) )

Emilien

**Comment by prium** [comment]
Hi,
Our UX expert said, "It's a bad UX" The menu become almost full screen in the smaller devices and user can not even see the page is moving if we keep the menu open. So we are keeping it as it is.

Thank you

**Comment by e2jk** [comment]
I'm not sure I'm following your response completely. You're indicating that it's a bad UX, that since the menu is almost full screen on smaller devices the user doesn't see the page has moved _if_ the menu stays open, but then you say we're keeping this as is?

The problem is that _because_ the menu stays open, the user doens't see the page has scrolled further. So making the menu disappear after a new location is selected will solve this issue. And that's the way the original Bootstrap theme behaves: large menu when you open it (that's the whole point why there is a menu in the first place instead of just showing the links, as the screen is so small), then the menu disappears when an item is selected.

**Comment by prium** [comment]
Ok, I got your point. I am reopening this issue. Waiting for pull request.
Thanks
